name: Download and Extract EPSS File

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:


permissions:
  contents: write

jobs:
  download-extract-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download EPSS .gz file
      run: |
        curl -L -o epss_scores.gz https://epss.cyentia.com/epss_scores-current.csv.gz

    - name: Extract and rename CSV file
      run: |
        # Extract the gz file (which will create a folder named like the csv)
        gunzip -k epss_scores.gz
        mv epss_scores epss_scores.csv

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epss_scores.csv
        git commit -m "Update EPSS data $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
