name: Download and Extract EPSS File - split year

on:
  schedule:
    - cron: '0 0,8,16 * * *'  # Every 8 hours
  workflow_dispatch:


permissions:
  contents: write

jobs:
  download-process-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download EPSS .gz file
      run: |
        curl -L -o epss_scores.gz https://epss.cyentia.com/epss_scores-current.csv.gz

    - name: Extract and rename CSV file
      run: |
        gunzip -k epss_scores.gz
        mv epss_scores epss_scores.csv

    - name: Split CSV by CVE year
      run: |
        rm -rf data
        rm -rf data_years
        mkdir -p data_years

        header=$(head -n1 epss_scores.csv)

        # Use awk to extract lines by year
        tail -n +2 epss_scores.csv | awk -v header="$header" -F, '
          BEGIN { OFS="," }
          {
            match($1, /CVE-([0-9]{4})-/, arr)
            year = arr[1]
            if (year != "") {
              file = "data_years/epss_scores_" year ".csv"
              if (!(year in seen)) {
                print header > file
                seen[year] = 1
              }
              print >> file
            }
          }
        '

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data_years/
        git add data/
        git commit -m "Split EPSS data by CVE year on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
