name: Download and Extract EPSS File - Split year and group

on:
  schedule:
    - cron: '0 1,9,17 * * *'  # Every 8 hours
  workflow_dispatch:


permissions:
  contents: write

jobs:
  download-process-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download EPSS .gz file
      run: |
        curl -L -o epss_scores.gz https://epss.cyentia.com/epss_scores-current.csv.gz

    - name: Extract and rename CSV file
      run: |
        gunzip -k epss_scores.gz
        mv epss_scores epss_scores.csv

    - name: Split CSV by CVE year and group
      run: |
        rm -rf data_groups
        mkdir -p data_groups

        header=$(head -n1 epss_scores.csv)

        tail -n +2 epss_scores.csv | awk -v header="$header" -F, '
          BEGIN { OFS="," }
          {
            if (match($1, /CVE-([0-9]{4})-([0-9]+)/, arr)) {
              year = arr[1]
              num = arr[2]
              group = substr(num, 1, 1)
              filename = "data_groups/epss_scores" year "_" group ".csv"
              if (!(filename in written)) {
                print header > filename
                written[filename] = 1
              }
              print >> filename
            }
          }
        '

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data_groups/
        git commit -m "Split EPSS data by CVE year and group on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
